# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 181, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../background pics/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-11, -1, 1031, 571))
        self.widget.setStyleSheet("background-color:rgb(0, 120, 0);\n"
"color:white")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 151, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../icons/DEVOE partners logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.Loginwidget = QtWidgets.QWidget(self.widget)
        self.Loginwidget.setGeometry(QtCore.QRect(420, 220, 351, 311))
        self.Loginwidget.setStyleSheet("background-color:rgba(0, 120, 0,0.7);\n"
"color: white;")
        self.Loginwidget.setObjectName("Loginwidget")
        self.lblUserName = QtWidgets.QLabel(self.Loginwidget)
        self.lblUserName.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.lblUserName.setFont(font)
        self.lblUserName.setStyleSheet("background-color: none;")
        self.lblUserName.setObjectName("lblUserName")
        self.loginbtn = QtWidgets.QPushButton(self.Loginwidget)
        self.loginbtn.setGeometry(QtCore.QRect(20, 230, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginbtn.setFont(font)
        self.loginbtn.setStyleSheet("#loginbtn{\n"
"background-color:rgb(171, 255, 14);\n"
"color: rgb(0, 120, 0);\n"
"font: 16pt \"Roboto\";\n"
"filter: box-shadow(100px 100px red);\n"
"}")
        self.loginbtn.setObjectName("loginbtn")
        self.lblPassword = QtWidgets.QLabel(self.Loginwidget)
        self.lblPassword.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("background-color: none;")
        self.lblPassword.setObjectName("lblPassword")
        self.label_6 = QtWidgets.QLabel(self.Loginwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 231, 41))
        self.label_6.setStyleSheet("font: 10pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:none;")
        self.label_6.setObjectName("label_6")
        self.BtnClickHere = QtWidgets.QPushButton(self.Loginwidget)
        self.BtnClickHere.setGeometry(QtCore.QRect(240, 277, 93, 28))
        self.BtnClickHere.setStyleSheet("font: 10pt \"Roboto\";")
        self.BtnClickHere.setObjectName("BtnClickHere")
        self.txtPassword = QtWidgets.QLineEdit(self.Loginwidget)
        self.txtPassword.setGeometry(QtCore.QRect(20, 140, 311, 40))
        self.txtPassword.setStyleSheet("#txtPassword{\n"
"background-color:rgb(255, 255, 255);\n"
"color:black;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.txtPassword.setObjectName("txtPassword")
        self.txtEmail = QtWidgets.QLineEdit(self.Loginwidget)
        self.txtEmail.setGeometry(QtCore.QRect(20, 60, 311, 40))
        self.txtEmail.setStyleSheet("#txtEmail{\n"
"background-color:rgb(255, 255, 255);\n"
"color:black;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.txtEmail.setObjectName("txtEmail")
        self.lblError = QtWidgets.QLabel(self.Loginwidget)
        self.lblError.setGeometry(QtCore.QRect(20, 190, 301, 31))
        self.lblError.setStyleSheet("#lblError{\n"
"background-color: none;\n"
"    font: 10pt \"Roboto\";\n"
"color:red;\n"
"}")
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(290, 20, 401, 41))
        self.label_4.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:none;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 800, 500))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../propertyPics/construction-concept-with-engineering-tools.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_3.raise_()
        self.Loginwidget.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblUserName.setText(_translate("MainWindow", "Email"))
        self.loginbtn.setText(_translate("MainWindow", "Login"))
        self.lblPassword.setText(_translate("MainWindow", "Passward"))
        self.label_6.setText(_translate("MainWindow", "If you Don\'t have an account."))
        self.BtnClickHere.setText(_translate("MainWindow", "Click Here"))
        self.label_4.setText(_translate("MainWindow", "Har Pata, Hamein Pata Hai"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
