# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowData.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.widget.setStyleSheet("background-color: green;\n"
"font: 12pt \"Roboto\";")
        self.widget.setObjectName("widget")
        self.TableWidgetData = QtWidgets.QTableWidget(self.widget)
        self.TableWidgetData.setGeometry(QtCore.QRect(0, 90, 800, 500))
        self.TableWidgetData.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Roboto\";")
        self.TableWidgetData.setRowCount(1)
        self.TableWidgetData.setObjectName("TableWidgetData")
        self.TableWidgetData.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidgetData.setHorizontalHeaderItem(7, item)
        self.cmbxSort = QtWidgets.QComboBox(self.widget)
        self.cmbxSort.setGeometry(QtCore.QRect(20, 30, 200, 35))
        self.cmbxSort.setStyleSheet("font: bold 12pt \"Roboto\";\n"
"background-color: white;\n"
"color: rgb(0,120,0);\n"
"")
        self.cmbxSort.setObjectName("cmbxSort")
        self.cmbxSort.addItem("")
        self.cmbxSort.addItem("")
        self.cmbxSort.addItem("")
        self.cmbxSort.addItem("")
        self.cmbxSort.addItem("")
        self.cmbxSort.addItem("")
        self.cmbxSort_2 = QtWidgets.QComboBox(self.widget)
        self.cmbxSort_2.setGeometry(QtCore.QRect(240, 30, 200, 35))
        self.cmbxSort_2.setStyleSheet("font: bold 12pt \"Roboto\";\n"
"background-color: white;\n"
"color: rgb(0,120,0);\n"
"")
        self.cmbxSort_2.setObjectName("cmbxSort_2")
        self.txtSearch = QtWidgets.QTextEdit(self.widget)
        self.txtSearch.setGeometry(QtCore.QRect(550, 30, 221, 40))
        self.txtSearch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"font: 12pt \"Roboto\";")
        self.txtSearch.setObjectName("txtSearch")
        self.lblSearch = QtWidgets.QLabel(self.widget)
        self.lblSearch.setGeometry(QtCore.QRect(730, 35, 30, 30))
        self.lblSearch.setStyleSheet("background-color:none;")
        self.lblSearch.setText("")
        self.lblSearch.setPixmap(QtGui.QPixmap(":/icons/magnifier.png"))
        self.lblSearch.setScaledContents(True)
        self.lblSearch.setObjectName("lblSearch")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(450, 30, 93, 35))
        self.pushButton.setStyleSheet("background-color: white;\n"
"color:rgb(0,120,0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cmbxSort, self.cmbxSort_2)
        MainWindow.setTabOrder(self.cmbxSort_2, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.txtSearch)
        MainWindow.setTabOrder(self.txtSearch, self.TableWidgetData)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.TableWidgetData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Agency Name"))
        item = self.TableWidgetData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Property Type"))
        item = self.TableWidgetData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.TableWidgetData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        item = self.TableWidgetData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Area"))
        item = self.TableWidgetData.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Purpose"))
        item = self.TableWidgetData.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "City"))
        item = self.TableWidgetData.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Contact"))
        self.cmbxSort.setItemText(0, _translate("MainWindow", "Sort By"))
        self.cmbxSort.setItemText(1, _translate("MainWindow", "Property Type"))
        self.cmbxSort.setItemText(2, _translate("MainWindow", "Price"))
        self.cmbxSort.setItemText(3, _translate("MainWindow", "City"))
        self.cmbxSort.setItemText(4, _translate("MainWindow", "Area"))
        self.cmbxSort.setItemText(5, _translate("MainWindow", "Purpose"))
        self.pushButton.setText(_translate("MainWindow", "Sort"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
