# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUpPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SignUpPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 181, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../background pics/icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-11, -1, 1031, 571))
        self.widget.setStyleSheet("*{\n"
"background-color:rgb(0, 120, 0);\n"
"color:white;\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.lblLogo = QtWidgets.QLabel(self.widget)
        self.lblLogo.setGeometry(QtCore.QRect(50, 20, 151, 71))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../../background pics/propertyPics/DEVOE partners logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setOpenExternalLinks(False)
        self.lblLogo.setObjectName("lblLogo")
        self.Loginwidget = QtWidgets.QWidget(self.widget)
        self.Loginwidget.setGeometry(QtCore.QRect(420, 150, 351, 341))
        self.Loginwidget.setStyleSheet("background-color:rgba(0, 120, 0,0.7);\n"
"color: white;")
        self.Loginwidget.setObjectName("Loginwidget")
        self.txtUserName = QtWidgets.QTextEdit(self.Loginwidget)
        self.txtUserName.setGeometry(QtCore.QRect(20, 140, 311, 41))
        self.txtUserName.setStyleSheet("#txtUserName{\n"
"background-color:rgb(255, 255, 255);\n"
"color: black;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.txtUserName.setObjectName("txtUserName")
        self.pswd = QtWidgets.QLabel(self.Loginwidget)
        self.pswd.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.pswd.setFont(font)
        self.pswd.setStyleSheet("background-color: none;")
        self.pswd.setObjectName("pswd")
        self.loginbtn = QtWidgets.QPushButton(self.Loginwidget)
        self.loginbtn.setGeometry(QtCore.QRect(20, 280, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginbtn.setFont(font)
        self.loginbtn.setStyleSheet("#loginbtn{\n"
"background-color:rgb(171, 255, 14);\n"
"color: rgb(0, 120, 0);\n"
"font: 16pt \"Roboto\";\n"
"filter: box-shadow(100px 100px red);\n"
"}")
        self.loginbtn.setObjectName("loginbtn")
        self.txtPassword = QtWidgets.QTextEdit(self.Loginwidget)
        self.txtPassword.setGeometry(QtCore.QRect(20, 220, 311, 41))
        self.txtPassword.setStyleSheet("#txtPassword{\n"
"background-color:rgb(255, 255, 255);\n"
"color: black;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.txtPassword.setObjectName("txtPassword")
        self.pswd_2 = QtWidgets.QLabel(self.Loginwidget)
        self.pswd_2.setGeometry(QtCore.QRect(20, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.pswd_2.setFont(font)
        self.pswd_2.setStyleSheet("background-color: none;")
        self.pswd_2.setObjectName("pswd_2")
        self.txtEmail = QtWidgets.QTextEdit(self.Loginwidget)
        self.txtEmail.setGeometry(QtCore.QRect(20, 50, 311, 41))
        self.txtEmail.setStyleSheet("#txtEmail{\n"
"background-color:rgb(255, 255, 255);\n"
"color: black;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.txtEmail.setObjectName("txtEmail")
        self.pswd_3 = QtWidgets.QLabel(self.Loginwidget)
        self.pswd_3.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.pswd_3.setFont(font)
        self.pswd_3.setStyleSheet("background-color: none;")
        self.pswd_3.setObjectName("pswd_3")
        self.lblQuote = QtWidgets.QLabel(self.widget)
        self.lblQuote.setGeometry(QtCore.QRect(290, 20, 401, 41))
        self.lblQuote.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:none;")
        self.lblQuote.setObjectName("lblQuote")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 70, 800, 500))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../propertyPics/construction-concept-engineering-tools.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.lblLogo.raise_()
        self.Loginwidget.raise_()
        self.lblQuote.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pswd.setText(_translate("MainWindow", "UserName:"))
        self.loginbtn.setText(_translate("MainWindow", "SignUp"))
        self.pswd_2.setText(_translate("MainWindow", "Passward:"))
        self.pswd_3.setText(_translate("MainWindow", "Email:"))
        self.lblQuote.setText(_translate("MainWindow", "Har Pata, Hamein Pata Hai"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = SignUpPage()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
