# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from muser import MUser
from SignUpPage import SignUpPage

class WelcomeWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.widget.setStyleSheet("background-color:rgb(0, 120, 0)")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 151, 70))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/DEVOE partners logo.png);\n"
"background-color:none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../background pics/propertyPics/DEVOE partners logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.LoginBtn = QtWidgets.QPushButton(self.widget)
        self.LoginBtn.setGeometry(QtCore.QRect(600, 0, 151, 91))
        self.LoginBtn.setStyleSheet("#LoginBtn{\n"
"background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 120, 0);\n"
"font: bold 16pt \"Roboto Black\";\n"
"}")
        self.LoginBtn.setObjectName("LoginBtn")
        self.SignUpBtn = QtWidgets.QPushButton(self.widget)
        self.SignUpBtn.setGeometry(QtCore.QRect(448, 0, 151, 91))
        self.SignUpBtn.setStyleSheet("#SignUpBtn{\n"
"background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 120, 0);\n"
"font: bold 16pt \"Roboto Black\";\n"
"}")
        self.SignUpBtn.setObjectName("SignUpBtn")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(160, 245, 481, 41))
        self.label_5.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(0, 120, 0);\n"
"background-color:none;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(160, 310, 501, 41))
        self.label_6.setStyleSheet("font: 20pt \"Roboto\";\n"
"background-color: rgb(0, 120, 0);\n"
"color: rgb(255, 255, 255);\n"
"letter-spacing: 5px;\n"
"padding: 80px;\n"
"border-radius: 20px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(440, 250, 91, 31))
        self.label_7.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(0, 120, 0);\n"
"background-color:rgb(0,120,0);\n"
"color: white;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(580, 250, 81, 31))
        self.label_8.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(0, 120, 0);\n"
"background-color:rgb(0,120,0);\n"
"color: white;")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(160, 250, 141, 31))
        self.label_10.setStyleSheet("font: 20pt \"Roboto\";\n"
"color: rgb(0, 120, 0);\n"
"background-color:rgb(0,120,0);\n"
"color: white;")
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(100, 200, 621, 191))
        self.label_4.setStyleSheet("background-color: rgba(255,255,255, 0.7);\n"
"border-radius: 20px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 90, 800, 500))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../propertyPics/beautiful-sunny-cityscape.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.LoginBtn.raise_()
        self.SignUpBtn.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.SignUpBtn.clicked.connect(self.ShowSignUpPage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoginBtn.setText(_translate("MainWindow", "Login"))
        self.SignUpBtn.setText(_translate("MainWindow", "SignUp"))
        self.label_5.setText(_translate("MainWindow", "Everyone  Wants a              of Land"))
        self.label_6.setText(_translate("MainWindow", "We made it easy"))
        self.label_7.setText(_translate("MainWindow", "Piece "))
        self.label_8.setText(_translate("MainWindow", "Land"))
        self.label_10.setText(_translate("MainWindow", "Everyone"))

    def ShowSignUpPage(self):
        SignUp = SignUpPage()
        SignUp.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = WelcomeWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
